### ISSUE TITLE
Creating callbacks in Rust for testing

### ISSUE THREAD

**Issue by elpiel** [ralfbiedert/interoptopus#117]
I'm struggling with creating a callback in Rust to do some tests within my code.

Is there a known pattern or a way to make this work with `extern "C" fn` in Rust?

```
  |
7 |     let callback = LoggingCallback::from(log_callback);
  |                    ^^^^^^^^^^^^^^^ the trait `From<for<'a> extern "C" fn(interoptopus::patterns::string::AsciiPointer<'a>) {log_callback}>` is not implemented for `LoggingCallback`
  |
  = help: the trait `From<for<'a> extern "C" fn(interoptopus::patterns::string::AsciiPointer<'a>)>` is implemented for `LoggingCallback`
  = help: for that trait implementation, expected `for<'a> extern "C" fn(interoptopus::patterns::string::AsciiPointer<'a>)`, found `for<'a> extern "C" fn(interoptopus::patterns::string::AsciiPointer<'a>) {log_callback}`

```

**Comment by ralfbiedert** [comment]
The underlying issue is probably related to #108, can you try `LoggingCallback(Some(log_callback))`?

**Comment by elpiel** [comment]
Ohh nice, that works. Thank you!

One downside to this approach is that the tuple field is private in the macro generated code.
Could we add a constructor (fn new) to the generated code to ease out this pattern when you don't create the callback in the same module?

**Comment by ralfbiedert** [comment]
The field could probably be pub, but some ctor would work as well. Would you mind filing a PR incl test?

**Comment by elpiel** [comment]
Yes I'm open to create a PR. 
Why do you want to have a ctor?

Can we just have a regular rust function instead? 
Is the only reason I would like to have a function is to be able to test in rust. 
Ctor might be excessive given that it cannot fail.

**Comment by ralfbiedert** [comment]
Sorry, was trying to be brief when typing on phone. Yes, with "constructor" I mean what I assumed you were referring to, an associated function that somehow creates that type, such as `MyCallback::from_fn(x: ...) -> Self`. That function should be public, and accept the correct `fn` parameter. Whether or not the `.0` field should be public I don't have strong opinions on at this point if you add that function. Probably someone might later ask for a getter, but we can add that then.
