### ISSUE TITLE
Patterns are Breaking Changes

### ISSUE THREAD

**Issue by Pspritechologist** [ralfbiedert/interoptopus#128]
At the moment adding any new patterns to Interoptopus is a breaking change. This is especially odd as the LibraryPattern enum clearly only exists to allow for further expansion, Service being the only variant right now. To allow adding new patterns without breaking working code would require LibraryPattern have the `#[non_exhaustive]` attribute added to it, which would require any matches made on it to have an infallible branch (such as `_ => {}`.). Unfortunately, adding this would *also* be a breaking change.

I'm making this issue under the assumption that new patterns *are* planned to be added at some point. Although waiting until such a time to add the attribute would make sense, it may also be a bandage worth taking off fast.

**Comment by ralfbiedert** [comment]
For upcoming 0.15 we can just add the attribute and handling in all backends.
