### ISSUE TITLE
gc handle vs fixed statement with pointer

### ISSUE THREAD

**Issue by dbenson24** [ralfbiedert/interoptopus#16]
Curious as to why the generated bindings use GCHandles instead of just passing a pointer to the slice inside a fixed statement

**Comment by ralfbiedert** [comment]
If you refer to functions like this:

```csharp
public static uint pattern_ffi_slice_1(uint[] ffi_slice) {
    var ffi_slice_pinned = GCHandle.Alloc(ffi_slice, GCHandleType.Pinned);
    var ffi_slice_slice = new Sliceu32(ffi_slice_pinned, (ulong) ffi_slice.Length);
    try
    {
        return pattern_ffi_slice_1(ffi_slice_slice);
    }
    finally
    {
        ffi_slice_pinned.Free();
    }
}
```

Without pinning the .NET runtime could relocate the memory while the FFI call is running. In other words, when you enter `pattern_ffi_slice_1` `ffi_slice` might reside at `0x1234`, but during FFI execution the CLR GC can move the whole array to `0x1000` if it wants to optimize memory layout. Since this could happen while Rust is still accessing the old location UB or an access violation would ensue. Pinning prevents that.

The reason `Sliceu32` in turn only accepts a `GCHandle` and not the `uint[]` array itself is that once an object is pinned, somebody needs to remember its proper lifetime and to unpin it, but `Sliceu32` has no reserved field for that, being a low-level primitive. In most cases the method overload handling pinning is the right place, as lifetimes are guaranteed to be correct, but if you need a "long-lived" FFI slice (which, I'd argue, is playing with fire from an interop perspective) you'll also need to handle proper pinning / unpinning (aka _lifetime semantics_) and race prevention elsewhere.

**Comment by dbenson24** [comment]
`public static uint pattern_ffi_slice_1(uint[] ffi_slice)
        {
            unsafe
            {
                fixed (uint* ptr = ffi_slice)
                {
                    var ffi_slice_slice = new Sliceu32(ptr, (ulong)ffi_slice.Length);
                    return pattern_ffi_slice_1(ffi_slice_slice);
                }
            }
        }
`
Yes, I agree that you need to pin the array so the GC doesn't move it. But you can also accomplish that using a "fixed" statement. Unless I'm missing something this is equivalent to what you have above except without allocating a GCHandle. I was looking in to swapping to interoptopus to generate C# bindings  for my raycasting code in rust and this was the difference between my hand made bindings and your generated ones. I'm now interested in trying out the gchandle approach to see if there's a performance difference.

**Comment by ralfbiedert** [comment]
Ah, `fixed` :) The main reason we use `GCHandle` is that C# `unsafe` needs to be enabled on a project level, which can be particularly invasive in Unity if you ship as a 3rd party library, as the whole game needs to be unsafe then. 

That said, there seems to be a performance difference of about ~30ns per call on my machine when using your example (and giving `Sliceu32` an `IntPtr` constructor):

```csharp
public static Vec3f32 pattern_ffi_slice_2_unsafe(Vec3f32[] ffi_slice , int i) {
    unsafe
    {
        fixed (Vec3f32* ptr = ffi_slice)
        {
            var ffi_slice_slice = new SliceVec3f32(new IntPtr(ptr), (ulong)ffi_slice.Length);
            return pattern_ffi_slice_2(ffi_slice_slice, i);
        }
    }        
}
```

Benchmark measurements:

| Method | nanos per call |
| ---- | ---|
| `pattern_ffi_slice_1(short_uint)` | 57 |
| `pattern_ffi_slice_1_unsafe(short_uint)` | 23 |
| `pattern_ffi_slice_2(short_vec, 0)` | 57 |
| `pattern_ffi_slice_2_unsafe(short_vec, 0)` | 26 |

I'm open to adding an `unsafe` option, as that difference is significant, and the change should be relatively localized; only affecting direct FFI overloads.

**Comment by dbenson24** [comment]
That would be fantastic

**Comment by ralfbiedert** [comment]
Version 0.8.1 is up which should address this; enable the `use_unsafe` config in the C# backend. 

Updated benchmarks:

Safe: 
  | Construct | ns per call |
  | --- | --- |
  | `pattern_ffi_slice_2(short_vec, 0)` | 66 |
  | `pattern_ffi_slice_2(long_vec, 0)` | 60 |
  | `pattern_ffi_slice_4(short_byte, short_byte)` | 104 |

Unsafe: 

  | Construct | ns per call |
  | --- | --- |
  | `pattern_ffi_slice_2(short_vec, 0)` | 28 |
  | `pattern_ffi_slice_2(long_vec, 0)` | 23 |
  | `pattern_ffi_slice_4(short_byte, short_byte)` | 29 |

**Comment by dbenson24** [comment]
thanks!

**Comment by ralfbiedert** [comment]
Quick follow up, I've now also tested this with accessing FFI slices in C#, and the performance difference is even more dramatic, up to 8x when doing heavy array lookup: 

  | Construct | ns per call |
  | --- | --- |
  | `pattern_ffi_slice_delegate(x => x[0])` | 195 |
  | `pattern_ffi_slice_delegate_unsafe(x => x[0])` | 52 |
  | `pattern_ffi_slice_delegate(x => x.Copied[0])` | 1307 |
  | `pattern_ffi_slice_delegate_unsafe(x => x.Copied[0])` | 161 |
  | `pattern_ffi_slice_delegate_huge(x => x.Copied[0])` | 11844317 |
  | `pattern_ffi_slice_delegate_huge_unsafe(x => x.Copied[0])` | 1484303 |

Now enabled in `interoptopus_backend_csharp` 0.8.3.

**Comment by dbenson24** [comment]
awesome! That is kinda what I was expecting. I think the difference is even larger in IL2CPP because GCHandles aren't as optimized in it as they are in Mono
