### ISSUE TITLE
Prevent emitting type declaration 

### ISSUE THREAD

**Issue by dbenson24** [ralfbiedert/interoptopus#32]
I've been looking around for this option and I don't think it exists. I'm basically looking to use types in function signatures like Vec3 or Mat4 which I already have full implementations of on the target language. I want the named types emitted in function signatures, but I don't want them declared on their own.
I'm happy to take a look at implementing this, I think it would make the most sense as an attribute on ffi-type

**Comment by ralfbiedert** [comment]
Sorry for the delay, just came back from vacation and am a bit swamped. Flavors of this came up before internally, but there are a few open questions:

- Handling between languages (e.g., C# should not emit, Python should)
- How to tell Interoptopus which substitute type to use; alternatively, how do you know which type to implement manually?
- How to express this in code?

About the last item, I agree FFI attributes are probably the best approach. However, there is some interdependence with language specific handling; and similar systems (e.g., language specific visibility, which we'd also like to have).

Tag ideas:

```rust
#[ffi_ignore] // Probably too simplistic, needs language specific handling
#[ffi_ignore(csharp)] // Maybe pass specific arguments?
#[ffi_tag(csharp; ignore)] // More general 'tagging' items which allows backends to consume these at will
struct S(u8);
```

There is also a trade-off between having a flexible system without compile time guarantees, and specific, well documented tags at the risk of noise. Right now I'm mildly leaning towards `ffi_ignore(...)` labels. 

With the tags done, what should a backend do when encountering such code (omitting other annotations for clarity):

```rust
#[ffi_ignore(csharp)]
struct S(u8);

extern "C" fn f(s: S) -> FFIOption<S> { ... }
```

It clearly should emit `f`, which might reside in a namespace `My.Company`. What about `FFIOption<S>`?
Also, in which file and namespace would your `S` reside, and how should that be added to the generated one? Also, what about helper methods we sometimes expect to be there, like for `FFISlice<S>`?

**Comment by ralfbiedert** [comment]
>  I'm basically looking to use types in function signatures like Vec3 or Mat4 which I already have full implementations of on the target language.

Ah, I forgot: A totally different approach would be to overload the interop calls with your types and call those instead. The Rust library won't mind, and you'd have to guarantee these types to be the same in any case.

**Comment by dbenson24** [comment]
No time pressure from me, I'm just using this for fun on the side. Thanks for all your work

In my head what I was thinking was that if I used #[ffi_ignore] on struct S then the only thing I would want my target language to skip emitting is the struct definition. I would still want all the generated option and slice types. I think then all I would need to ensure all my stuff compiles without manual editing of the generated file is an include_str on the generator that lets you specifiy some code to go into the header for your use/import statements

**Comment by dbenson24** [comment]
fwiw #39 addresses this entirely, I can just ignore the types I want to after the inventory is created

`fn my_inventory() -> Inventory {
    let mut ignore_types = HashSet::from([
        "BoundingBox",
        "BoundingBoxD",
        "Double3",
        "Float3",
        "QuatD",
    ]);
    InventoryBuilder::new()
        .register(function!(init_logger))
        .register(function!(build_bvh))
        .register(function!(rebuild_bvh))
        .register(function!(query_ray))
        .register(function!(batch_query_rays))
        .register(function!(query_sphere))
        .register(function!(query_capsule))
        .register(function!(query_aabb))
        .register(function!(query_obb))
        .register(function!(free_bvh))
        .register(function!(add_node))
        .register(function!(remove_node))
        .register(function!(update_node))
        .register(function!(flatten_bvh))
        .inventory().filter(|x| {
            match x {
                InventoryItem::CType(ty) => {
                    let name = ty.name_within_lib();
                    if ignore_types.contains(name.as_str()) {
                        return false
                    }
                }
                _ => ()
            }
            true
        })
}`

**Comment by ralfbiedert** [comment]
Thanks for heads up! Let's close this ticket for now, can reopen if needed.
