### ISSUE TITLE
FFISlice points to garbage data if called from a simple function, as opposed to a service

### ISSUE THREAD

**Issue by Skippeh** [ralfbiedert/interoptopus#38]
Not sure if i'm doing something wrong, but i'm fairly sure i'm not...

If you have an FFISlice<T> parameter in a function it seems to point to garbage data or something on the rust side. But moving the same function to a service makes it work like expected.

I made a project as an example:

https://github.com/Skippeh/interoptopus_slice_issue

Outputs:
![image](https://user-images.githubusercontent.com/420685/154862317-d752d9d3-aaaf-4686-8546-60c0fc54c054.png)

It seems to behave the same on 0.13.15. Haven't tried earlier versions.

I have only tried C# but i think the problem is in the rust code.

**Comment by ralfbiedert** [comment]
I can reproduce the issue in your sample, but the issue seems to be a missing `extern "C"`. Once I change your function to 

```rust 

#[ffi_function]
#[no_mangle]
pub extern "C" fn print_slice_func(slice: FFISlice<u8>) {
    println!("{:?}", slice.as_slice());
}
```

It works:

```
Calling service...
[1, 2, 3, 4]
Calling func...
[1, 2, 3, 4]
```

The reason services work is we expand that for you:

```rust
#[interoptopus::ffi_function]
#[no_mangle]
#[allow(unused_mut)]
#[allow(clippy::needless_lifetimes)]
pub extern "C" fn print_service_print_slice(context: &PrintService, slice: FFISlice<u8>) -> MyError {
    ::interoptopus::patterns::result::panics_and_errors_to_ffi_enum(move || {
        <PrintService>::print_slice(
            context, slice)
    }, stringify!(print_service_print_slice ))
}
```

That said, it would be nice if `#[ffi_function]` warned about the missing ABI specifier.

**Comment by Skippeh** [comment]
Oh shit, turns out i'm just stupid! 👍

Thanks for the quick response.
