### ISSUE TITLE
C backend should handle c_char type as char rather than integer

### ISSUE THREAD

**Issue by pixsperdavid** [ralfbiedert/interoptopus#41]
Currently `c_char` type parameters get transformed to `int8_t` in the C backend. This results in all FFI function calls accepting a C string as input (`*const c_char`) to generate header files which express this in a way that requires a cast to `*int8_t` to use. Ideally the C backend should transform `c_char` type into `char`.

Happy to look at this myself proving there's no good reasons against this behavior?

**Comment by ralfbiedert** [comment]
I think this is an oversight, a PR attempting to fix this is very welcome. Feel free to ask if you run into issues.
