### ISSUE TITLE
Convert rust document comments into C# style

### ISSUE THREAD

**Issue by ZhaoXiangXML** [ralfbiedert/interoptopus#80]
Is it possible to convert rust document comments into [C# style](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments) so we can generate C# API document with it?

for instance:
```rust
/// This function has documentation.
#[ffi_function]
#[no_mangle]
pub extern "C" fn documented(_x: StructDocumented) -> EnumDocumented {
    EnumDocumented::A
}
```

should be convert to:
```csharp
/// <summary>
/// This function has documentation.
/// </summary>
...
```

**Comment by ralfbiedert** [comment]
No this isn't supported, and it's _in general_ not on the roadmap. Main reason is Interoptopus is a general-purpose generator, and it would be impossible to properly satisfy all Python, C#, ... documentation tags.

I would, however, accept PRs that automatically inserts _some_ tags that can easily and universally be inferred (e.g., create `summary` from first Rust summary sentence), but that's about it.

**Comment by ralfbiedert** [comment]
Tentatively closing since I have no intention of implementing this any time soon. That said, if someone feels very strongly about this and drives a PR that works sufficiently I'd be open to revisit this.
