### ISSUE TITLE
`FFISlice` and similar do not adhere to Rust's naming convention

### ISSUE THREAD

**Issue by tbu-** [ralfbiedert/interoptopus#99]
According to convention, you'd call them `FfiSlice` and similar.

From https://rust-lang.github.io/api-guidelines/naming.html#casing-conforms-to-rfc-430-c-case:
> In `UpperCamelCase`, acronyms and contractions of compound words count as one word: use `Uuid` rather than `UUID`, `Usize` rather than `USize` or `Stdin` rather than `StdIn`.

**Comment by ralfbiedert** [comment]
Closing, I think this won't be fixed unless we renamed the `FFI` part to something else.

**Comment by tbu-** [comment]
Probably just needs some getting used to it. `Uuid` is the same, and it's of course helpful for users of a library if it's consistent with the ecosystem.
